# Generated by Django 3.2.7 on 2021-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0002_auto_20210926_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='test1', max_length=50),
            preserve_default=False,
        ),
    ]
